### ISSUE TITLE
how to use it in chrome extensions

### ISSUE THREAD

**Issue by NeverBeLazyG** [travisvn/openai-edge-tts#6]
Hello friend. this is very cool.
is there a way to use this in chrome extensions which have openai api input settings ? like in the screenshot. is there any way to mimic it that the extension thinks its connecting to original openai. or some other solution ?

<img width="329" alt="Screenshot 2024-10-23 143332" src="https://github.com/user-attachments/assets/f1172af7-2c95-4429-9d30-1ad6d355cd6e">

**Comment by travisvn** [comment]
@NeverBeLazyG So, the underlying Python package that powers this project, `edge-tts` (https://github.com/rany2/edge-tts), achieves "free" Edge TTS calls by emulating the calls made by the Edge web browser. 

In the Microsoft Edge web browser, which is a Chromium-based web browser, you can right-click anywhere and select "Read Aloud" and Microsoft provides free, high-quality text-to-speech. 

If you'd like to make use of this, then you should switch to Microsoft Edge https://www.microsoft.com/en-us/edge

**Comment by NeverBeLazyG** [comment]
na, all my infrastructure is chrome based. i dont like the edge.whould be nice if there would be a possibility to use it via extension in chrome
